Repository graphprotocol/indexer, pull requests merged in 2024-06, with the labels that each got.

#906 service: Increase size of attestation signer cache
  packages/indexer-service/src/allocations.ts
Labels: bug

#898 docs: added base, bsc, scroll and linea to the feature support matrix
  docs/feature-support-matrix.md
Labels: documentation

#901 Indexer-service: Server integration tests
  packages/indexer-service/jest.config.js
  packages/indexer-service/package.json
  packages/indexer-service/src/server/__tests__/server.test.ts
Labels: hardening

#914 indexer-common: Avoid using createdAt field for pagination
  packages/indexer-common/src/indexer-management/__tests__/helpers.test.ts
  packages/indexer-common/src/indexer-management/monitor.ts
Labels: bug

#932 Cleanup migration 12
  packages/indexer-agent/src/db/migrations/12-add-scalar-tap-table.ts
  packages/indexer-common/src/query-fees/models.ts
Labels: TAP

#934 common: Add support for BSC, Base, Linea, Scroll
  packages/indexer-common/src/indexer-management/types.ts
Labels: enhancement

#935 common,agent: fix tsconfig, error-handling export
  packages/indexer-agent/src/commands/start.ts
  packages/indexer-agent/tsconfig.json
  packages/indexer-common/src/parsers/index.ts
Labels: bug
